default_platform(:ios)

desc "Run release for the platform specified in the branch name"
lane :deploy do
	setup_ci

	app_store_connect_api_key(
		key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
		issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
		key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"]
	)

	sync_code_signing(
		type: "appstore",
		app_identifier: ["build.miguel.PokeDex"],
		readonly: true,
		platform: "ios",
		additional_cert_types: [],
	)

	increment_build_number(
		build_number: latest_testflight_build_number + 1,
		xcodeproj: "PokeDex.xcodeproj"
	)

	build_app(scheme: "PokeDex", xcargs: "-skipMacroValidation")
	upload_to_testflight(distribute_external: true, changelog: "", groups: ["External"])
end

desc "Generate profiles and certificates"
lane :generate_profiles_and_certificates do
	sync_code_signing(
		type: "development",
		app_identifier: ["build.miguel.PokeDex"],
		readonly: false,
		platform: "ios"
	)

    sync_code_signing(
      type: "appstore",
      app_identifier: ["build.miguel.PokeDex"],
      readonly: false,
      platform: "ios"
  )
end
